-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:8889
-- Généré le :  mar. 03 déc. 2019 à 10:17
-- Version du serveur :  5.7.26
-- Version de PHP :  7.3.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `mvc_blog`
--

-- --------------------------------------------------------

--
-- Structure de la table `article`
--

CREATE TABLE `article` (
  `art_id` int(11) NOT NULL,
  `art_title` varchar(255) NOT NULL,
  `art_content` text NOT NULL,
  `art_media` varchar(100) NOT NULL,
  `art_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usr_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `article`
--

INSERT INTO `article` (`art_id`, `art_title`, `art_content`, `art_media`, `art_date`, `usr_id`) VALUES
(1, 'Quidem qui eos quod deleniti pariatur eos aut rerum.', 'Vero ipsam doloremque aut dolor ex. Iusto veritatis porro ut sint aut dignissimos. Dolores voluptas beatae omnis eum. Ducimus ut est maxime rerum natus aut. Perferendis ex adipisci nesciunt animi voluptatem dolor enim. Aliquam qui sequi occaecati id qui. Expedita deleniti illo blanditiis aut maiores. Sapiente praesentium dolorum quia fugit veniam at. Voluptas architecto vero sint consequatur ut consequatur. Error eius voluptatem et aspernatur est id dolores. Est quaerat ad quidem ipsam explicabo quo autem. Fugiat repellat maiores laborum distinctio et ducimus recusandae. Reiciendis aspernatur id molestiae. Aut autem omnis est ut omnis consequatur enim. Aliquam fugit nisi rerum ad est voluptatem eos. Voluptas mollitia labore enim natus. Nobis delectus error occaecati rerum molestiae ut voluptate. Eos eveniet ullam minima aliquam tenetur et. Nemo quidem deleniti velit officiis. Rerum tenetur voluptas voluptatem ut exercitationem asperiores. Maiores et fuga repellendus ratione. Voluptatem excepturi odit assumenda dolor atque laudantium. Blanditiis consequatur molestias totam blanditiis consequatur est. Mollitia quaerat est adipisci. Dolores et dolores repudiandae et assumenda quia. Ut magni harum non et dolorem iusto. Illo qui officiis sunt beatae est eum soluta quia. Consectetur voluptatem voluptas eaque velit. Maxime sit consectetur veniam ut corporis quo veritatis. Aliquid voluptatem eveniet est unde. Architecto sed possimus ducimus deleniti voluptate. Et quia expedita dolorem vero eos veritatis est quos. Aut quia ea tempore velit ea. Voluptas quo blanditiis rerum velit ab repellendus et. Ut est nesciunt eaque. Quibusdam quod facilis facere sed debitis totam in. Consequatur velit dolores quae incidunt ipsum unde temporibus odio. Architecto aut error eius ut rem molestiae deserunt. Dolorum in qui omnis nemo. Optio error ea commodi ea qui. Quibusdam repellendus culpa qui reprehenderit voluptatem. Nulla voluptas officia aut rem ipsum ut voluptas. Sed praesentium mollitia accusantium assumenda ut quae. Optio nostrum sit sit laborum architecto. Numquam ut nihil nihil perferendis quis voluptas cum.', '1.jpg', '2019-11-13 23:07:19', 17),
(2, 'Modi recusandae qui veniam.', 'Odit sed non laudantium enim et dolores saepe. Tempore omnis est optio sed. Dolores voluptas veritatis deleniti corporis possimus. Quia rerum rem corrupti tenetur. Quis quis exercitationem reiciendis ipsum culpa atque molestias. Possimus odio accusantium excepturi repellat officia doloremque. Odio eos vitae beatae aliquid accusamus deleniti. Delectus esse id maiores accusamus.', '2.jpg', '2019-10-14 10:36:55', 5),
(3, 'Rerum eligendi necessitatibus non aut mollitia commodi.', 'Magnam omnis numquam quaerat earum debitis autem distinctio sint. Velit sint dolor quia modi sint nesciunt laudantium qui. Iusto quidem et perspiciatis ut eaque illo sint. Minima sed mollitia eveniet. Magni assumenda sit veritatis ullam. Nobis adipisci in eos necessitatibus et rerum non. Corporis hic qui sit sunt. Qui quas dolores debitis aut. Distinctio eos soluta odit earum pariatur iusto omnis. Odit est consectetur explicabo sit nesciunt soluta. Facilis facilis sint esse maxime aut facere maxime. Non ut quia porro quis. Aperiam assumenda et rem. Aut id rerum quae quam aut totam. Aut ipsam et sed omnis consequatur quis. Quibusdam architecto accusantium aperiam soluta. Quod hic fugiat et et qui sunt ut et. Et et in velit sapiente ducimus. Et laborum est commodi repudiandae reiciendis. Dolores reprehenderit assumenda perferendis expedita. Animi enim vitae tempora neque iste et est. Quas sed ex quod.', '5.jpg', '2019-10-12 13:36:56', 19),
(4, 'Dolores sint est ad earum voluptatem culpa.', 'Voluptatibus et nihil ipsa est vitae quia. Voluptatem qui excepturi ut qui natus atque et. Ipsam veniam consequuntur earum animi quia unde cupiditate. Et autem assumenda temporibus repellat. Possimus repellat aut nostrum omnis voluptas. Sed ab voluptatem quibusdam provident aut est. Vero aut ratione voluptas ipsa saepe itaque natus. Necessitatibus nostrum voluptatem quis doloribus quia. Fugiat temporibus laudantium delectus animi. Maiores eum dolores cumque iure eligendi voluptas. Amet accusamus laboriosam sequi quisquam. Repellendus sed sed autem vel et distinctio ea. Animi accusamus libero perferendis quas maxime doloribus molestiae. Et architecto placeat magni eum atque corporis. Similique non dolorem necessitatibus voluptas assumenda sed. Recusandae quia est fuga est veritatis animi quidem suscipit. Eum voluptatem aut itaque quod. Quisquam vero fuga vero facere beatae dolores minus ut. Quos sed illum natus consequatur. Et sit magni beatae voluptatem repellendus illo. Voluptas et vel et provident. Vel voluptatem adipisci eum iste doloribus. Pariatur nobis hic labore cumque. Possimus minima hic incidunt velit quis unde. Ut ea autem aut sed eos. Repellat sed modi id nostrum ad. Tempore dolorem alias odit. Et maxime sint doloremque perferendis possimus. Neque reiciendis odio veniam excepturi qui aut. Qui tenetur beatae quia natus quia. Corporis voluptas inventore ex velit vel. Non voluptatem est aperiam dolorem ut recusandae vero.', '4.jpg', '2019-11-16 07:56:57', 8),
(5, 'Sit tenetur sint sit.', 'Tempore quo explicabo at voluptate beatae consequuntur quia. Quis ut voluptate iste aut quos. Aut quaerat quia consequatur enim id nisi iusto.', '5.jpg', '2019-09-29 06:39:57', 17),
(6, 'Est sunt dolore eligendi numquam omnis commodi.', 'Quis exercitationem unde et voluptatem mollitia sit minima. Sed aliquid odit a esse. Et ipsum et amet. Porro nisi aut mollitia autem at earum. Labore assumenda veritatis molestias quia repudiandae. Alias natus voluptas sunt eum eius laborum qui. Quis eum consequatur reprehenderit debitis. Saepe in sapiente impedit.', '3.jpg', '2019-11-04 18:15:58', 2),
(7, 'Porro velit sunt earum optio ex aliquam eum veniam.', 'Inventore aut nobis id sit itaque error vitae. Voluptas asperiores animi harum velit nisi delectus molestias. Consequuntur et omnis recusandae temporibus sequi. Modi magnam debitis voluptatem doloremque. Est similique ullam odit suscipit. Rerum nobis blanditiis nobis saepe praesentium. Aliquid veritatis id eos. Accusantium earum enim minus omnis sint. Ut aperiam et iusto omnis magni. Voluptatem quaerat quia fugit sapiente maxime odio corrupti. Est beatae amet nobis et qui perspiciatis. Facere id et consequatur accusantium. Laborum blanditiis ut in similique placeat. Ad alias et laborum sit eum. A modi ut quas eum voluptate unde omnis in. Voluptatem et dolor delectus quas. Magni iure enim facilis quos perspiciatis rerum et. Quia voluptatum accusantium quia maiores praesentium maxime repudiandae. Molestiae accusamus voluptate commodi. Consequatur consequatur expedita pariatur ut enim eius perferendis. Velit repellat nihil repellat reprehenderit consequatur dolores. Molestias reprehenderit in accusamus autem pariatur deserunt. Accusamus adipisci ut reprehenderit odio. A minus ipsam fugit eos ex expedita. Id aut et repellendus et inventore omnis. Alias quam qui natus eius cupiditate eius. Exercitationem omnis omnis suscipit quos ab consequuntur consequatur. Autem quis aut repudiandae et ea dolorum. Expedita quia possimus omnis autem qui. Vitae et et eos eum nihil sed facilis. Illum non veniam accusamus harum fugit fugiat nihil. Labore ullam aliquid distinctio. Qui quasi esse voluptas accusantium omnis illum distinctio. Asperiores sequi voluptates eligendi. Aliquam amet quia eius cumque eaque. Earum eveniet pariatur facilis beatae hic et. Totam quae doloribus ut et. Vitae alias dolores numquam quibusdam at. Blanditiis illo aspernatur quisquam. Vero dolores et vero quo cumque. Sint dolore quidem quod cumque distinctio nostrum atque. Rem aut quae sit voluptas officiis sint. Tenetur dolorum tempore eum voluptate cupiditate sit vero. Et aliquid qui blanditiis debitis suscipit inventore amet. Dolor quaerat consequatur dolorem voluptate eum assumenda beatae. Repellendus voluptas natus perferendis doloribus modi. Et et eum rerum qui voluptatum. Voluptatem hic laborum non quidem nostrum aut architecto. Cum doloremque vitae molestiae voluptatem et. Non et est voluptas aperiam cum facere aut. Aspernatur et libero dolorum quis et labore doloribus. Harum aut veniam temporibus quasi earum qui doloribus. Aliquid ea consequatur iusto autem qui et adipisci ut. Provident quae explicabo perspiciatis quasi consequatur. Sapiente quisquam est et est necessitatibus ut. Molestias consequuntur facere eveniet corporis. Iste iste laudantium vel. Quidem laudantium nostrum voluptatem ipsum explicabo nesciunt. Illo ratione repudiandae vero ipsum dolor. Ipsam modi voluptatem fugiat placeat ex sapiente. Dicta nostrum inventore et labore ut mollitia suscipit tenetur.', '7.jpg', '2019-10-20 01:41:59', 15),
(8, 'Et officiis tempora.', 'Laborum aliquid fugit quidem esse velit et aut. Voluptas voluptas commodi et quisquam. Ut saepe ipsa qui nulla explicabo nisi eaque. Quidem explicabo consequatur adipisci molestias tempore ut inventore. Et architecto id nisi quae numquam. Sed sed pariatur iusto aliquid cumque est enim aut. Quaerat sequi molestias ea assumenda. Pariatur accusamus id non aspernatur tempora est. Ut adipisci eligendi fugiat libero a. Sit sed et sint rem. Recusandae sint aperiam quo sed voluptates ut hic. Qui distinctio cumque placeat ut ea temporibus. Voluptatem porro tempora quibusdam soluta velit quos omnis a. Pariatur aspernatur eaque exercitationem aut voluptas. Cupiditate sit magni voluptatum non sapiente accusantium quos. Necessitatibus aut expedita sed expedita dolorum aliquid beatae ab. Et non doloribus eum tempore eos omnis. Praesentium architecto quia dolore amet voluptas odio. Nihil voluptates et dolor explicabo. Laborum ex libero consectetur. Qui voluptatem illum vitae quia consequatur qui. Nemo animi rerum eos sit. Porro dicta omnis est est voluptatem. Atque provident quos nihil est provident. Nulla id aspernatur consectetur et reiciendis quia odio quis. Quaerat quia repudiandae sint quod voluptate. Labore eaque voluptatibus libero omnis et. Repellendus ut repellat et dignissimos voluptas aspernatur molestiae. Ut perspiciatis odit qui earum rerum. Deserunt libero doloremque dolor temporibus sint voluptatem sed commodi. Qui laborum temporibus sit repudiandae quas rerum. Magnam adipisci voluptatem quaerat sint autem assumenda. Tempore esse et rerum et. Veritatis illum alias et quis autem nam. Dolorem aut quisquam consectetur. Iste libero quis suscipit rerum et omnis vel id. In consequuntur et magnam laboriosam accusantium dolore tenetur. Provident nostrum dolorum id debitis voluptatem eveniet ducimus. Vitae ratione qui vel vel et. Consequatur totam rerum doloribus omnis id. Voluptatem facere natus maxime quas labore. Neque dolor officia itaque et vitae beatae.', '8.jpg', '2019-10-21 18:55:00', 11),
(9, 'Pariatur optio consequatur voluptas.', 'Autem cupiditate iste ut modi ipsam nisi eos. Qui voluptas fuga alias quaerat quam nostrum assumenda. Sunt corporis cumque qui vel soluta sequi vero debitis. Deserunt aperiam at numquam aut quae. Enim dolor nisi ea dolorem earum. Esse quisquam consectetur labore blanditiis et alias. Vero aut quisquam aut. Facilis autem maxime eum commodi fugit sunt quos quidem. Inventore et libero quis quo sit. Labore consequatur accusamus voluptatibus tenetur. Et quod sequi laborum quo optio voluptas mollitia. Alias quia reprehenderit sed voluptatem ut corrupti. Eum enim ipsa iusto iste quia perspiciatis. Vero nobis placeat blanditiis et labore est. Atque non aliquam voluptatum totam natus. Sit repellat ex consectetur ut est ea ut. Reprehenderit nihil ex ea iste est. Dolorem dolor qui earum et voluptates sit. Ut ut nihil molestiae doloribus. Est non natus ex molestiae. Ex minima ut provident nobis. Qui dolorum fuga eligendi veniam voluptate similique id. Est aut quos nisi aperiam itaque culpa hic. Totam laborum fugiat eligendi consequatur voluptas magnam perspiciatis ad. Accusamus et voluptas earum sed quia consequuntur. Autem corporis molestias fugit cum. Sed voluptatem perferendis eos quas molestiae et laboriosam laboriosam. Eum totam labore dignissimos sit perspiciatis commodi vero. Placeat delectus nulla expedita voluptates et temporibus. Placeat dolor deleniti qui magnam magnam minus nam ipsa. Consequatur quasi illo culpa aliquam optio consequatur commodi et. Libero perferendis ab unde iste dolor et qui quia. Labore tempore sed facilis sit. Illum quis est cupiditate nihil. Nisi enim asperiores et id. Sint sint non iusto. Neque nobis nihil non necessitatibus in ratione.', '3.jpg', '2019-11-13 08:13:00', 15),
(10, 'Aliquam tempora aut veniam vitae assumenda mollitia aspernatur nulla.', 'Exercitationem sapiente amet officia repudiandae ad et. Aut beatae asperiores est molestiae. Quia ipsum autem expedita nesciunt. Quae temporibus accusamus quo eius. Vel ea voluptas error nam explicabo velit.', '6.jpg', '2019-10-09 12:36:01', 12),
(11, 'Sed odio asperiores fugiat incidunt sed et.', 'Ipsam nulla omnis et commodi aut ut. Recusandae aut quisquam et numquam fugiat quia explicabo. Qui molestiae dolor eos voluptatibus voluptas nihil. Hic et ab qui quia repudiandae cum. Blanditiis nisi sint tempore nobis accusamus id. Id fugit aut est velit. Reiciendis nihil ab beatae. Voluptates molestiae sint eos possimus natus saepe iste. Eum sit voluptatibus eligendi dolorem quia ab. Exercitationem quis ad autem reiciendis et tenetur. Sed et rerum quas minima. Vero magni laudantium ab enim et. Consequatur facere quibusdam voluptas. Pariatur aspernatur possimus ut et. Quis quibusdam fugiat voluptatibus et excepturi. Recusandae corrupti unde unde non vel est sunt. Molestiae debitis non rerum labore et eaque. Sit delectus quisquam cupiditate omnis debitis numquam itaque. Quia excepturi et possimus et sunt. Saepe soluta doloribus tempore et dicta. Nulla vero veritatis autem atque dolores ut quos. Eum necessitatibus officiis rerum iste ducimus praesentium. Omnis id consequuntur quod placeat unde ratione id. Est ea veniam officia consequatur adipisci quibusdam quae. Similique fugit facere est voluptatum assumenda quia. Aut excepturi qui repellendus voluptatem dignissimos perspiciatis suscipit neque.', '5.jpg', '2019-09-17 22:47:02', 9),
(12, 'Sed est laborum possimus nihil molestiae illum.', 'Suscipit eaque magni voluptatem sed voluptas repudiandae. Ea tenetur distinctio repellendus veritatis quibusdam voluptatem sint. Provident quasi asperiores sint vel ut non praesentium. Sit explicabo aspernatur rerum earum. Nisi voluptas vero quam et cupiditate labore impedit. Exercitationem non maiores optio laborum ducimus consectetur. Dolores repudiandae quibusdam inventore eum. Accusantium debitis mollitia nostrum nulla beatae natus deserunt. Consequatur totam rerum velit. Vel est ab nemo et deleniti explicabo. Non rerum mollitia autem aut. Dolorum maxime nam aut. Quia sunt facere laudantium atque odit debitis ea. Quo quia iste laboriosam ipsa et tempora. Velit eius eligendi veniam vel qui consectetur et. Consectetur minus maiores sunt est. Nulla inventore voluptatibus sit atque. Fugiat exercitationem aliquid esse omnis laudantium cumque aut sunt. Esse non ea nihil quam saepe voluptatem suscipit. Quas ea consequatur quia ut qui debitis. Rerum voluptatem cumque rem quos incidunt voluptas. Consequatur velit temporibus temporibus et. Fuga atque iste quis voluptatem veniam labore et. Qui et veniam velit ducimus delectus ea corporis. Quidem voluptas autem aspernatur et consectetur labore id enim. Assumenda explicabo eum facere et harum. Fuga consequatur iure ut. Excepturi eaque eos culpa quasi et assumenda a. Cum voluptatem facere inventore. Et quod quibusdam natus quibusdam ea eum. Eos exercitationem asperiores hic consequatur quis praesentium consectetur. Vero illum aut eum quos facere. Sapiente doloremque qui ipsum facere perspiciatis voluptatem incidunt. Autem fugit quam animi magni. Aspernatur adipisci excepturi quia deserunt labore quo sit voluptas. Error ratione atque excepturi officia natus sed. Quos animi fuga qui consequatur facere. Qui consequuntur quia eligendi earum velit velit deserunt. Vel consequatur laudantium quod. Quia suscipit et quis. Qui soluta illum optio dolorem earum quam. Perspiciatis vel consequuntur aperiam distinctio eaque est. Sint accusamus fugiat vel voluptate aut. Aliquid sint iste autem itaque alias id. Natus consequuntur dolores est quisquam magnam sequi. Eveniet esse ipsum animi nemo. Ipsam labore beatae tenetur consequatur facilis necessitatibus. Dolore explicabo nihil beatae aut suscipit. Ratione qui vel saepe nam voluptas unde voluptate. Sunt at veniam enim quia doloremque. Et qui harum modi qui. Laborum sit dolores sit distinctio odio et. Asperiores minus vel voluptas omnis earum. Molestiae sit quas reiciendis omnis et dolorem. Aut libero dolores dolorum aut et nesciunt. Fugit tempore placeat repudiandae eaque eos rerum quo laboriosam. Laboriosam voluptas consequatur possimus tempore soluta doloribus eius. Repellendus et sapiente ut aut. Eos eos eius dignissimos occaecati tenetur et. Cupiditate sapiente aspernatur quia ex quam. Autem nemo et sunt voluptatem.', '8.jpg', '2019-09-29 15:13:03', 2),
(13, 'Modi voluptatem ad qui ratione ut aliquam id.', 'Saepe et rerum ut aut accusantium. Perferendis aliquid asperiores dolore quia. Corrupti quaerat cumque doloremque quaerat veniam sint iusto ut. Repellendus itaque qui quas dolores dignissimos. Odit culpa sed voluptatibus autem qui iusto. Magnam omnis et quam vel dolore ut omnis. Dolores repellendus nisi quis. Laudantium non ut incidunt rem dolor. Ut est eligendi quo recusandae ullam est odio. Nobis omnis consequatur qui quisquam ipsa. Minima ut voluptatibus consequatur. Ullam optio modi natus recusandae blanditiis sapiente sunt. Labore nam id culpa exercitationem doloremque eaque neque. Ratione quidem eaque aut aut tempore commodi. Fuga tempore ut nemo omnis quis quia libero. Dolore hic cum enim nisi dolorum natus praesentium et. Occaecati sint perspiciatis aut qui. Ratione minus repellat eius qui laboriosam consequatur incidunt. Accusamus debitis libero magnam magni aut. Eos et suscipit velit nam ut eos saepe. In repellendus vel architecto quaerat quia placeat nesciunt. Sunt sed sunt cum error similique eaque officiis omnis. Deserunt ipsa ipsa quo tempora accusamus recusandae repellat. Voluptate alias reprehenderit reprehenderit ducimus libero. Reiciendis voluptatem eos eos molestias temporibus vitae. Dolores aut vel recusandae soluta. Reiciendis ipsam eius a voluptas occaecati officia. Reprehenderit enim incidunt ea dolorem. Iusto omnis totam voluptas quam earum vel. Tempore voluptatem labore aut. Ea accusamus quos in rerum mollitia deserunt consequuntur fugiat. Ea qui suscipit quas fuga voluptatum sint.', '5.jpg', '2019-10-16 17:05:03', 7),
(14, 'Sed animi necessitatibus iste dolorem quos.', 'Ea natus tempora magni nostrum voluptatum odio qui. Culpa labore sed molestiae quibusdam et ipsam optio quos. Pariatur laudantium aut voluptatem mollitia dolorem molestiae sit. A neque veritatis sapiente ex. Eius eos debitis ratione laborum. Id blanditiis ex accusamus sit corrupti aut vel. Iusto enim unde eum aspernatur. Illum minus hic molestias sit qui. Officiis dicta asperiores voluptatem iusto sit quibusdam fugiat. Nihil quis nam maxime voluptas. Sit qui qui nesciunt placeat ducimus numquam doloribus natus. Ratione quia distinctio facere ipsum dolorum molestiae totam. Corporis porro magni explicabo minima sed fuga ab. Atque nostrum dolore illum aut quisquam pariatur aut. Recusandae blanditiis sit recusandae suscipit et dolorum. Delectus voluptas quidem qui et ratione adipisci maiores consectetur. Saepe illum rem sint reiciendis accusantium ut. Inventore nobis voluptas blanditiis magni ipsum in cupiditate enim. Molestiae et et non laboriosam. Consectetur architecto aliquid ducimus. Voluptas omnis voluptatem ut tempora. Aut sit in occaecati ea molestiae est est. Quam nihil quisquam veniam quia autem alias perspiciatis. Expedita non quaerat hic expedita et dolorum. Nobis delectus qui neque sit culpa aut. Quisquam qui id sint exercitationem. Iusto quia voluptatem nostrum rerum. Recusandae quibusdam alias vel aliquam. Illum ducimus voluptate quidem alias quis. Dolor deserunt architecto aut enim voluptatem. Quae exercitationem architecto repudiandae iusto voluptates tempore placeat quis. Soluta consectetur veniam nobis porro sunt. Et consequatur et dicta omnis vitae. Eveniet minima explicabo consectetur aut facilis occaecati.', '2.jpg', '2019-10-13 19:56:04', 19),
(15, 'Expedita quo ut sed quis ad saepe aut.', 'Iste occaecati vel rerum consequatur commodi itaque. Illo et sit odit quidem. Harum sit id soluta ipsam quo id. Consequuntur omnis ab illum error cumque nisi magnam enim. Adipisci laboriosam quis tempore harum sint. Ullam facere deleniti et sint. Minus voluptas officia laboriosam tenetur labore. Ut exercitationem qui quo dolore expedita. Consequatur occaecati reiciendis consequatur ea et ducimus dolorum nemo. Corporis fugit voluptatibus adipisci a labore eius. Perspiciatis repellendus fuga aut ducimus voluptas et beatae. Aperiam illo beatae ex. Rerum aut alias vero voluptas sunt aut. Corrupti est natus est itaque non quis quas cum. Praesentium labore dicta temporibus in iure ex. Nihil cupiditate voluptatem deserunt nesciunt cumque incidunt. Quod quia fugiat ducimus totam officiis velit eveniet. Aut adipisci facere voluptatum maiores eum dignissimos quidem. Ut id quo asperiores. Voluptatem sed vel et aut temporibus accusamus quis. Sint molestiae voluptas dolor mollitia reprehenderit delectus rerum. Qui omnis reiciendis modi at asperiores. Libero ut rerum labore cum eveniet quam. Nulla eligendi reiciendis fugiat ut ex. Explicabo iure voluptates quos qui error fugiat totam. Perferendis qui ipsa consequuntur quam. Omnis perspiciatis error eum aut molestiae facere at. Repellat consequatur dignissimos et mollitia dolor dolorem et. Dolorem ducimus fuga aut dicta. Earum et enim quo in est est. Blanditiis adipisci eos sequi minima. Corrupti vel nobis nobis nihil alias. Qui sequi et reprehenderit beatae neque et dolor. Est ad exercitationem quia illo eius dolore animi modi. Voluptas molestiae ut similique fugiat consequatur. Enim debitis qui nostrum voluptas molestiae harum. Inventore placeat tempore modi magnam alias.', '1.jpg', '2019-11-11 13:36:05', 16),
(16, 'Voluptate et delectus error.', 'Modi reprehenderit tempora voluptatibus porro similique et. Tempora eum inventore dignissimos eos. Cumque amet deleniti est sit qui. Aut aut autem et dolorem accusamus. Sunt possimus odio velit et excepturi. Voluptatem in ea hic. Vel dicta dolorem eaque ea asperiores et est quia. Vero in modi odio aut nostrum id. Odit omnis dignissimos natus et itaque aliquam. Laboriosam alias qui eveniet impedit ut consequatur. Delectus ut quod et perspiciatis ad laudantium recusandae. Animi reprehenderit fugiat at sapiente aut itaque. Consectetur nihil veniam possimus. Ipsa qui minima dignissimos id architecto. Dolorem nihil quam voluptatem qui voluptatem.', '5.jpg', '2019-10-02 12:50:05', 4),
(17, 'Perferendis aperiam facilis eos ad ratione officia.', 'Maxime necessitatibus explicabo et quibusdam. Unde et exercitationem voluptas molestias voluptatem non aperiam. Fugiat eum rerum vel quo sed repellat dolorum. Ut fugit aliquid omnis et eos eligendi et. Ex nobis distinctio molestiae ipsam qui magnam sit. Perspiciatis voluptatem sed rerum aut. Natus quo iure dicta sit sed deserunt. Accusamus sit et enim est quibusdam magnam ut. Ut nemo praesentium atque et modi atque aut. Et iusto est aliquid id quia dicta. Sit saepe qui quo non sapiente aut maxime. Laudantium quisquam beatae cumque modi eum dolores facere. Minima consequuntur atque ut odit ipsa magni ut. Et dolore illum illo est. Provident porro omnis dolore sint fugiat nostrum voluptatibus. Quisquam quis nulla eum cupiditate quidem. Non qui in id id nesciunt veniam. Minus dolor officia velit nisi aliquid.', '4.jpg', '2019-10-21 06:52:06', 18),
(18, 'Vero voluptas doloribus eum quis iure.', 'Nostrum tempora asperiores voluptatem aut. Sunt sit dolor alias optio placeat ipsam. Necessitatibus quibusdam ex fugiat consequatur minima earum ab. Similique alias numquam quod eum laudantium. Mollitia ut autem in quas et debitis id. Itaque accusamus iusto nesciunt aut. Quaerat impedit distinctio asperiores sint est non. In aut labore qui tenetur. Neque quas et qui sed est nulla molestias. Quis laborum dolores magnam et. Nam est voluptas porro reiciendis modi doloribus. Aut quibusdam reiciendis rerum aut quos dolor. Aperiam libero magni autem est perferendis amet. Ut necessitatibus quia autem accusamus id qui soluta. Doloribus non iure nemo. Aut et modi aut. Consequatur sint ducimus eius exercitationem ipsam quis rerum vel. Veniam laborum voluptate ut eveniet. Soluta autem occaecati illum amet tempore. Tenetur architecto voluptas labore laudantium quia. Vero velit ducimus et praesentium impedit et harum. Ipsa dolorem ipsa aperiam itaque accusantium. Quod veniam ut debitis. Dolores mollitia sit fuga. Error quidem voluptas sit veniam et esse. Nihil molestiae ducimus ut consectetur. Repudiandae animi perferendis voluptas est quia et sit ut. Illo iure et distinctio quis. Aut odit omnis maxime sint incidunt. Iure molestiae vitae a molestiae itaque eaque. Impedit autem dolor corporis id sequi. Quo est nemo unde delectus. Sit necessitatibus beatae aut tenetur voluptatibus. Earum ratione sint nesciunt error. Consequatur provident et exercitationem perferendis enim quia ut. Consequatur fugit laudantium provident voluptas eaque qui nihil beatae. Sit id dolorem id dignissimos. Repudiandae ut dolorem voluptatem omnis. Nemo sint enim at tenetur. Est aut hic id officiis deserunt voluptatum enim. Sit quo laboriosam eius dolorum occaecati perferendis. Velit in et quis dolorem modi. Nam sint libero vitae harum et eum qui aliquam. Cupiditate et reprehenderit voluptatum harum ullam debitis. Sequi et quibusdam perspiciatis dolor. Iste nesciunt veniam voluptatibus. Dolorem eum vel possimus dolores.', '5.jpg', '2019-09-30 02:08:07', 16),
(19, 'Velit dolores voluptatum consequatur.', 'Earum dolorem sed saepe dolores non voluptatem. Unde sed autem voluptas. Error doloribus eligendi rerum ex. Consequatur voluptatem deserunt asperiores modi minima rerum numquam. Non error sit qui deserunt ut. Et consectetur iusto unde fuga quia non non exercitationem. Deserunt ut voluptas soluta aliquam omnis. Natus quam est sed libero qui sapiente ad. Ullam error labore soluta non quis repellat eos. Non qui alias quasi est et vitae. Odio aliquid nisi laboriosam sed vel culpa. Iste repudiandae sunt rerum qui. Aut omnis quos et error quam eligendi ipsum. Iste voluptatem beatae deserunt est rerum. Illum unde enim possimus dolores voluptate vero saepe similique. Voluptatem rerum et accusamus voluptatem. Sunt voluptatem aut voluptas corrupti fuga reiciendis asperiores. Omnis et ut dolor placeat incidunt ut voluptas aut. Ipsum porro distinctio repellat nesciunt modi ut. Quas soluta repellendus aut vel velit sit nostrum aut. Sed eaque temporibus est omnis. Cupiditate optio nobis culpa dolore. Numquam modi sit qui atque labore non maxime. Delectus sequi dolor est ex ea voluptatem debitis. Ex et nulla cum aliquid rerum. Numquam cupiditate quae in. Eos aut et sed laborum. Sit natus beatae facilis qui molestiae sed. Ipsam voluptatem et quia libero quisquam. Itaque molestiae dolorem consequuntur sit. Soluta adipisci tempora dolores repellat animi sed. Id harum aut atque voluptate. Quia vero porro laborum consectetur. Non et voluptatibus sed voluptatem. Et exercitationem voluptas dicta alias tempora numquam eligendi. Ut et voluptates quas dolores itaque quo numquam. Ut sed labore esse laudantium rerum nam accusamus.', '5.jpg', '2019-11-09 00:07:07', 8),
(20, 'Delectus culpa fuga et expedita recusandae.', 'Ex molestias dolorum alias at corporis. Consequatur sit voluptatibus fuga inventore minus. At vitae dolor sed molestiae. Minus consequatur vel dolore voluptatem quia iusto at. Quia laboriosam corporis illo officiis veniam fugiat ut. Consequatur consequatur est voluptatem optio repellendus atque eligendi. Eius nobis repudiandae ducimus minima. Similique quidem eum qui qui. Aut ut aut ipsam natus. Quam qui placeat quia quisquam. Maxime enim quidem ipsum aut. Iusto sed est omnis sapiente voluptatem. Rem animi amet et enim. Voluptatem repellendus nihil velit dolores vel id est est. Id commodi odit eveniet debitis incidunt autem aperiam. Nihil rerum unde libero non eos vero ab. Ut quos enim aut suscipit debitis voluptatem. Nisi aut quas voluptate veritatis quos eius doloremque. Quo dolore vitae velit. Eaque aut maiores optio natus non voluptatum dolores. Expedita dolorum vel nulla deleniti deleniti. Error nesciunt enim expedita corporis deserunt voluptas aspernatur. Cum quia sed omnis qui occaecati enim. Ducimus atque in consequatur. Odit saepe ex quia voluptate adipisci voluptatibus sed voluptatem. Repellendus quia odit quasi deserunt aliquam dolorem. Nam aperiam dolorem deleniti velit quod. Molestiae nisi neque earum officiis.', '2.jpg', '2019-11-18 17:09:08', 14),
(21, 'Iste ut vitae optio et nesciunt voluptatem ipsum omnis.', 'Ea temporibus quam ea inventore. Sequi sed voluptas quasi. Expedita eaque maiores nihil velit sint molestias numquam. Nobis ullam vero beatae autem accusamus soluta id. Consequatur non omnis quas qui voluptatem. Id nobis provident nulla veniam perferendis. Ut optio nobis eligendi et vel. Adipisci nihil aut unde excepturi sunt. Aut nam repudiandae fugit velit. Voluptate unde praesentium saepe nesciunt suscipit sint et veritatis. Ipsam voluptates distinctio repellendus fugiat laudantium facere rerum. Modi odit sit totam saepe sed aut quidem. Eum maiores dolorum at nulla et molestiae consequuntur. Sit qui et dolores. Quo quaerat cumque voluptatem voluptatem. Deserunt omnis eos ut excepturi. Possimus autem et aut quidem vel numquam doloremque. Temporibus quam qui sequi ducimus blanditiis. Aut vel cum ea libero voluptatem sint et. Repellendus natus animi cupiditate pariatur sapiente. Rerum nam sapiente inventore possimus sed cupiditate ducimus. Tempore qui ut quidem similique quaerat nam ipsum.', '5.jpg', '2019-10-01 01:22:09', 5),
(22, 'Aspernatur harum et et ad nihil consectetur aut.', 'Esse voluptate amet odit officia qui esse aut. Ipsam illum quam molestiae deleniti voluptatibus.', '1.jpg', '2019-09-21 23:19:10', 17),
(23, 'Eos eveniet necessitatibus et et.', 'Est nam nemo doloremque quidem labore tempora. Quasi nam quod repudiandae dolorum voluptatibus quia. Quidem et asperiores aut illum amet. At ut quia dolore in velit. Distinctio temporibus quis dolor debitis. Alias ipsa atque reiciendis possimus omnis minus suscipit. Fuga sed sit reiciendis dolor sit beatae. Ipsum nam eum eos officia consequuntur doloremque et soluta. Iure minima et minus harum sint laudantium. Eos numquam blanditiis dolores quidem eligendi consequatur. Officia adipisci voluptas et maxime sit est maxime. Ut sequi in vitae dolores.', '5.jpg', '2019-09-13 23:10:10', 19),
(24, 'Sed qui tenetur enim non voluptas deserunt.', 'Eligendi eligendi voluptatem ratione et ipsa. Quisquam nihil omnis reiciendis fuga voluptates aut. Et voluptas qui vero minus cum voluptatem. Praesentium sit libero perferendis dolor. Alias repellendus voluptas vel enim aut. Exercitationem quis perspiciatis laudantium et. Adipisci veniam exercitationem ipsam. Unde ea dolorem aut quae minus. Et in explicabo a quidem odio. Eos deserunt labore occaecati quo natus repellendus. Eos odio sequi at explicabo aut. Doloremque quas id fugit velit qui ab. Molestias quidem recusandae ipsum omnis pariatur cum nam. Et sint harum est. Aut perferendis molestiae enim. Nobis quidem deserunt modi asperiores possimus vel. Debitis iure reprehenderit autem officiis sequi. Cumque voluptatem commodi aut deserunt. Omnis ipsa et magni. Velit sed est soluta id iusto. Modi est cum nobis. Explicabo voluptate laborum excepturi sed qui. Et deleniti unde saepe eum. Harum et et doloribus incidunt maxime. Quia voluptas quos quae fugit modi magni. Temporibus voluptas impedit ut quae. Voluptas maxime corporis quibusdam eum. Inventore praesentium occaecati velit corrupti doloribus sint. Repellendus distinctio officiis dolores mollitia. Suscipit doloremque fugiat est quis dolore. Quaerat facilis eos omnis qui nobis. Illum pariatur possimus doloribus aut ut et. Accusamus vitae tenetur qui accusamus eaque. Itaque praesentium neque maxime est a et. Omnis vel labore aperiam. Nihil facere nihil cumque sunt. Et doloremque commodi rem commodi. Quae tempora modi rerum molestiae quidem aut. Et a tempore autem accusamus et totam. Iste ut aspernatur explicabo. Qui laboriosam provident voluptatem. Qui laudantium beatae accusantium eum. Praesentium eum deleniti aut doloribus dolor magni unde quia. Quas minus est voluptas ipsa. Nihil vero delectus placeat qui. Quaerat mollitia dolores temporibus deserunt autem distinctio et. Ipsa possimus eos quaerat illo cumque. Natus exercitationem sequi qui voluptatibus. Architecto aut sequi pariatur. Qui ut qui et ut delectus maxime reprehenderit. Vitae explicabo harum aliquid architecto ullam blanditiis. Blanditiis natus expedita hic nihil. Similique distinctio in praesentium sint. Reiciendis aut et aliquam maiores nisi consequatur. Mollitia iste odit sit voluptatem quam magnam voluptates. Voluptatem occaecati fugiat at natus. Quis doloribus repellat odit minus possimus sint vel. Nobis explicabo laboriosam ullam itaque. Reprehenderit est repellat sed et voluptatum. Adipisci sequi et magni atque autem non consequatur. Velit aspernatur repellat vel libero voluptatibus omnis.', '4.jpg', '2019-11-03 14:18:11', 8),
(25, 'Ad quis pariatur quaerat corporis.', 'Ex quibusdam voluptas dolor quae aut voluptatem sed. Itaque et sunt voluptatem quidem reiciendis. Eligendi nam possimus eos est nulla. Inventore aut officiis ratione ab vitae voluptatem sint. Praesentium mollitia aliquid odio. Sint quia dolorem voluptates maxime numquam et. Veniam et hic commodi. Est soluta enim dolores aliquid animi maxime vero. Et rerum iste officia. Magni voluptatem at ut assumenda optio nisi. Iste distinctio quae ad neque. Eveniet sit accusamus maxime. Sunt iusto dolorem dolores assumenda soluta. Ad debitis ducimus nihil. In eum reiciendis neque officia accusantium reprehenderit reprehenderit assumenda. Expedita aut qui sapiente iusto ex. Non quibusdam explicabo aut rerum quae a. Enim ea ut quia quam et vero quo. Aliquid est ducimus autem cum. Molestiae distinctio quis vel ut deleniti voluptatem unde et. Repudiandae sequi aspernatur in. Et saepe nemo est consequuntur dolor. Odio velit laudantium aut rerum. Maiores iste et consequatur sed. Qui quia et aspernatur modi deleniti. Incidunt in incidunt quae omnis et iusto similique. Molestias laborum tempora sunt voluptas qui adipisci. Ut laudantium fugit culpa. Dolores et magnam placeat qui nihil blanditiis. Dolor voluptatibus ipsam tempora qui beatae nostrum beatae. Dolorum autem consequatur nulla porro. Quo fugiat nam omnis quisquam aut. Odio modi qui rerum tempore asperiores voluptatem. Quibusdam officiis quos eaque. Et odit sunt cum voluptatem atque. Quis optio at ab dolores vel et sit. Qui possimus non occaecati enim expedita. Amet porro velit nihil voluptas ut aliquid iste dolorum. Qui ipsam unde impedit veritatis reprehenderit animi dolor. Recusandae dicta alias qui reiciendis at libero. Veniam a nisi earum. Et impedit veritatis eligendi enim fugiat. Culpa excepturi commodi cum. Et sequi saepe aliquid nihil est voluptas veniam. Dolor ex aut numquam consequatur cupiditate dolore debitis expedita. Impedit sequi nisi vitae itaque et atque quas. Alias minus at quaerat consequatur iure dignissimos odit dolores. Odit reiciendis tempora perferendis consequatur libero voluptatem ab aspernatur. Quis maiores omnis qui iusto nam unde et. Modi soluta maxime ipsum odio aspernatur id. Tenetur harum deleniti voluptatem minus vel. Qui omnis qui est tempora. Id molestias qui repellendus dicta pariatur qui. Et est aliquam earum pariatur est animi soluta. Tenetur dolorem illo nostrum voluptatem quas asperiores voluptas et. Esse voluptas qui ut dolor iusto deleniti. Numquam ut facilis reprehenderit et quod dicta dolores. Est sunt soluta et eum quia. Molestiae tempore esse ut hic sint tempora consequuntur. Deleniti fugiat enim sunt. Perspiciatis qui eveniet et molestiae cum libero facere. Consectetur quae consequatur temporibus nobis fuga laborum eum reiciendis.', '5.jpg', '2019-10-09 07:35:11', 19),
(26, 'Qui deserunt sunt accusantium repellat consequatur eaque placeat libero autem.', 'Nisi aspernatur nesciunt ut in sed. Laborum doloremque et numquam sit dolore tempore nam. Pariatur ipsa quaerat eos laudantium et et repudiandae. Mollitia placeat praesentium iusto ut fuga natus dolores esse. Ipsa natus aut quod. Est dolore dolorum voluptas veniam. Totam est perspiciatis quia temporibus atque necessitatibus necessitatibus. Dolorem amet repellat eos ipsam voluptates unde. Doloribus laudantium aut tempore nam. Sunt voluptas aperiam eos autem porro.', '1.jpg', '2019-11-18 12:28:12', 12),
(27, 'Quas vel unde qui velit magni.', 'Molestiae ut quo doloremque voluptatem illo dolorum id. Quas sapiente alias dignissimos. Aut sapiente non tempora delectus non rerum. Molestiae ea temporibus dolor distinctio perferendis repudiandae assumenda. Rerum eos blanditiis recusandae nemo voluptate eos et. Nam dignissimos qui laborum praesentium. Quia nihil non reiciendis nesciunt qui. Eum ut ut reprehenderit maxime velit. Sed asperiores praesentium minima eaque et. Mollitia maxime animi laborum nemo magnam tempore. Magnam tenetur et et optio hic dolore unde sint. Odio aut debitis ratione ratione dolor consequatur. Itaque nobis et blanditiis sapiente. Autem voluptatem illo autem fugiat accusamus excepturi velit. Labore corporis aut veritatis maxime voluptatem autem. Unde nemo dignissimos corporis ipsam rem totam. Magni recusandae ipsum eveniet quasi et inventore. Deserunt eligendi dolores expedita sint totam ut. Quia dolores consequatur ratione qui nihil rerum adipisci. Placeat illo unde quia fugit ea nam quia. Alias ullam ut voluptate aut at. Repellat odit eligendi suscipit ut esse velit magni. Voluptas harum officiis autem sed debitis veniam rem. Voluptatem laboriosam rerum est quis id ipsum alias corporis. Et sit adipisci consequuntur dolorum itaque. Ratione et rem soluta deleniti. Nihil nesciunt voluptatibus sint. Explicabo sapiente ab asperiores corporis. Eaque eaque dolor et. Dolorem odio tempora voluptate et doloremque. Voluptas iste modi autem odio. Qui autem perspiciatis tempora quod doloribus earum. Distinctio eos amet sit ratione alias quia. Nemo et similique nemo quibusdam qui sit fugiat. Consequatur pariatur amet repellendus voluptatum. Illo corrupti excepturi quo voluptas illum. Quasi itaque dolor eos. Molestias non illum aliquam quod. Omnis voluptate quia reprehenderit suscipit. Saepe distinctio quia expedita quia. Sint et voluptates aspernatur repellendus suscipit laboriosam voluptates.', '5.jpg', '2019-11-10 06:32:14', 13),
(28, 'Explicabo velit in sed illum cupiditate.', 'Dolore eveniet rerum ut et est quia. Quos incidunt quaerat voluptatum. Voluptatem adipisci laudantium saepe consequatur occaecati id. Voluptatem sit neque maiores non consequatur mollitia veniam. Non quis excepturi corrupti et. Sunt optio placeat ullam quia cupiditate id molestiae et. Cumque veritatis nihil provident est deleniti. Asperiores vel harum et. Sit vero eum error quidem eos earum ut dolorem. Veniam quae fugiat facilis hic. Quae non et amet quos non in cumque illo. Eum impedit ut alias qui et excepturi. Cupiditate laboriosam pariatur neque exercitationem rerum alias ipsa. Vero qui quasi inventore porro ducimus. Aut quasi libero voluptas sit cum impedit. Repellendus similique sed nostrum doloremque libero pariatur et alias.', '2.jpg', '2019-09-24 06:31:15', 14),
(29, 'Incidunt perspiciatis quia dolorum ullam inventore quam exercitationem fugiat adipisci explicabo.', 'Aliquid facere saepe laborum quidem aut culpa quibusdam. Molestias nobis et nisi qui ipsa porro. Et velit vel sit reiciendis. Voluptas est sequi necessitatibus repellat aut. Aut aut quas tempore ea tempora tenetur.', '5.jpg', '2019-10-15 12:56:15', 4),
(30, 'Cupiditate et tempora magnam doloremque sequi ut est molestias.', 'Doloremque tempore voluptatibus neque alias eaque. Corporis et fugit distinctio cupiditate suscipit repellat occaecati. Sint rerum qui amet voluptates officia unde. Quis error quia modi officia. Suscipit hic quaerat culpa et qui eos omnis in. Sed nulla exercitationem possimus numquam optio et. Odio sed sapiente natus qui voluptate assumenda quia dolores. Itaque velit repellat fuga fugiat ut voluptates. Est officia ipsum vel repellat autem molestiae facilis. Illo vel minus laboriosam ea. Quo numquam fugiat sapiente commodi sed. Placeat ratione eos voluptate voluptatibus dolores et nihil. Voluptatem quam hic beatae aperiam qui in consequatur dolores. Iusto voluptates perferendis aperiam rem nihil. Non nisi voluptas ea a excepturi. Ea sit et aut quis. Sit sit numquam sit. Rerum quia porro optio est minima id nulla. Minima a minima quia ea commodi. Pariatur aliquam laudantium repudiandae est est. Ut aliquid non enim consequuntur sunt.', '5.jpg', '2019-11-15 21:07:16', 8),
(31, 'Odio vitae iste dolore ea.', 'Incidunt eius accusamus est tempore ab magnam. Ex dicta ducimus alias sapiente expedita aperiam. Consequuntur odit rerum qui similique. Vel nulla qui et odit sit ut sit. Iusto aut at quis sunt architecto tempora dolorum repellat. Cupiditate et mollitia nemo officia dolores dolores. Ea beatae voluptates laborum facere adipisci sed quaerat. Ipsam qui omnis molestias. Et qui laboriosam dicta laborum. Non explicabo labore enim nemo iusto quis ut totam. Corporis et consequatur exercitationem consequatur ipsum omnis voluptas. Nesciunt corporis eius enim et vero porro doloribus et. Ipsum quam tenetur nam eaque sunt sed. Provident eligendi earum fuga qui recusandae. Veniam accusamus voluptatem ducimus. Unde reiciendis rerum sit laudantium amet et. Qui exercitationem vero quaerat harum laborum. Impedit sed et et. Sunt voluptatum nisi quos reiciendis eum odit. Maxime voluptatum fugiat et ipsa ut quo quasi. Omnis aspernatur sapiente labore saepe adipisci aut inventore. Doloribus autem alias quo omnis aliquam. Occaecati ipsam quo qui dolore consequatur qui veniam. Libero laboriosam quod minus dolorum praesentium aut.', '5.jpg', '2019-10-09 18:12:17', 2),
(32, 'Vero ullam non pariatur qui aspernatur at est expedita et.', 'Autem rerum iusto voluptas est qui iste. Et qui molestiae sunt excepturi. Rem sit tempora voluptatibus placeat. Ex voluptas nam et eaque architecto et. Ut cumque ducimus nobis suscipit sequi. Blanditiis aut quia debitis eos. Rem voluptatibus praesentium officiis aut voluptate et. Dolorem quam aut libero quis quia. Est magnam iure sed natus reiciendis excepturi. Fugit quisquam molestiae praesentium vel ut. Dolorem asperiores sit minus totam quia veritatis nihil. Tenetur aut ea aut corporis consequatur dicta id. Aut in earum illo iure. Earum vel assumenda qui autem id. Sunt ut eius placeat voluptate in. Unde voluptas voluptatem voluptatem minus iusto ducimus non quia. Aliquid perferendis qui ut ut. Repellendus mollitia voluptatem alias dolorem voluptatem velit sed. Dolor sit occaecati in. Ut optio eligendi eveniet assumenda autem corrupti possimus. Nesciunt ut natus magnam est sunt dolorum quia. Quia error neque saepe expedita molestiae est odit. Laboriosam voluptatem et sed. Nihil aliquid dicta iste quam est ipsam quibusdam. Praesentium vitae possimus et dolorum. Voluptas magni consequatur saepe quis ratione assumenda unde. Est ipsam aut sint laudantium. Dolorem qui temporibus suscipit facere omnis quia sapiente. Accusantium aut quod est eaque praesentium iure consectetur. Et distinctio ipsa natus aut eum illum illum. Autem temporibus consectetur qui facilis voluptas sed. Qui nobis quam est magnam velit dolore. Debitis est quae itaque. Laboriosam harum delectus eius nesciunt sed inventore. Magnam pariatur reiciendis soluta mollitia. Aperiam quo id qui. Modi neque molestiae aperiam ipsam. Laborum iste quibusdam quas iure nihil doloremque doloribus. Deleniti vel temporibus hic qui sit. Dicta beatae animi esse hic repellat consequatur non. Ut fugit doloremque aspernatur dolorum eos. Eaque et ut placeat quis ipsum fuga ducimus non. Quasi in ducimus rem. Quam id saepe et aut. Asperiores fugiat rerum itaque est itaque aut. Reprehenderit animi dicta ea reiciendis enim tenetur libero. Ab est voluptatem perferendis totam rerum facilis. Labore fugiat et magni sit. Occaecati maxime quia eos. In voluptas ipsum atque. Doloremque reiciendis facere nam quis. Dolores aperiam tenetur non modi. Facilis atque in corporis voluptas sit. Ut rerum beatae beatae praesentium et. Nostrum est sit sint vel dolorum. Dolore ad quam ut laborum dignissimos odio assumenda. Voluptas iste dolorum iusto qui dicta veritatis. Provident natus dolor at modi veritatis impedit doloremque. Voluptate molestiae ullam eos ipsum. Nihil maxime aperiam incidunt non omnis. Consequatur nihil explicabo et quaerat deleniti sint quos. Vel et accusamus explicabo omnis quis.', '5.jpg', '2019-11-05 11:31:53', 16),
(33, 'Voluptatum illum omnis est tenetur aspernatur harum vel mollitia sapiente.', 'Minus earum corrupti fuga dolorem ea quia. Exercitationem deserunt nam repellat tempore aut libero. Rerum saepe reiciendis veniam rerum est. Illo accusamus incidunt maxime optio nesciunt. Est ullam qui quasi sunt ea. Consequatur laboriosam ipsa voluptatem eius in repellendus beatae quis. Unde aut quo nisi quisquam. Esse aut eum voluptas ut hic. Aut consequatur temporibus possimus exercitationem eum sed totam. Quos ut ullam veritatis delectus recusandae ipsum aut ut. Sunt dolor deleniti reprehenderit sit deleniti. Vitae maiores quo eaque fugit. Consequuntur aut similique incidunt adipisci rerum. Odio repellat adipisci quae eveniet quidem. Sit placeat et et. Fugit ipsum error quia quia maiores ut. Sed perferendis atque molestias fugit libero. Voluptatem odio doloribus numquam magnam itaque quaerat qui ullam. Quidem qui possimus nihil aut consequatur quam tempora eaque. Qui nihil adipisci qui voluptates vitae enim voluptatibus. Commodi id minima distinctio ipsa consequuntur in ullam et. Iusto dolorum est qui sunt aperiam. Non sint voluptas quae doloremque quia tempora. Numquam suscipit tempore blanditiis consequatur tempora quae rerum. Ipsam dolorem commodi et cum et reiciendis reprehenderit. Voluptatibus sed amet dolores sunt. Neque sit ducimus fugiat rerum facilis quia odio temporibus. Vel omnis cupiditate sint placeat deserunt. Quis reprehenderit veritatis aliquam maxime dolores labore aut. At voluptates nesciunt vel omnis placeat aliquam nesciunt. Porro reprehenderit et et non deleniti corporis et. Aliquam est recusandae sapiente quia cum. Molestiae ut in illum ut qui. Nisi quibusdam aspernatur rerum veritatis velit et vel. Tenetur repellat dolore a modi temporibus hic. Ut neque officiis aut maiores eius.', '5.jpg', '2019-10-07 19:18:54', 16),
(34, 'Accusamus nihil temporibus earum qui cupiditate magni rerum consequatur animi odit.', 'Adipisci beatae distinctio aut. Et quod architecto voluptate laudantium aut eum cumque. Qui quae ut at aut. Est ipsum fugit est laudantium. Omnis perferendis molestias et iure non provident. Odit illum necessitatibus architecto quidem voluptas omnis pariatur. Ipsam aliquid et et quos quas qui. Voluptas architecto occaecati deserunt. Perferendis iste ullam est placeat. Qui ea voluptas maxime quod voluptatibus eligendi esse. Nihil molestiae voluptatem sunt quibusdam quo mollitia voluptatem. Non aspernatur et blanditiis illum natus qui.', '5.jpg', '2019-11-20 11:25:54', 3),
(35, 'Omnis nam consequuntur architecto maxime iusto laborum praesentium quia.', 'Laudantium rerum non fugit id aspernatur rerum suscipit. Fuga tempore dolorem magni recusandae. Eligendi doloremque neque ratione sit id neque ratione.', '5.jpg', '2019-10-24 03:22:55', 17),
(36, 'Voluptates error velit alias facilis architecto et facere deserunt soluta doloremque.', 'Sed aperiam amet provident. Nulla explicabo voluptatum aut accusantium quisquam illo voluptatem. Sed sed numquam cupiditate est explicabo ea ex. Sunt sed fugiat accusantium rerum laboriosam eos quisquam alias. Et cum expedita rem totam laborum rerum. Consectetur temporibus non accusantium labore sapiente. Libero asperiores iste consectetur neque harum adipisci aut. Id similique sapiente animi adipisci ut porro. Quos accusantium accusantium itaque quidem facilis. Quos qui ut cupiditate iure deleniti aut voluptatem recusandae. Aut et quod dolores consequatur. Porro consequatur accusamus sequi et officia. Eveniet voluptatibus sint dolor tempore odio eos perferendis. Iusto eveniet modi hic molestiae pariatur. Aut eum voluptate ipsum qui facilis reprehenderit. Iusto maxime molestias aliquid dicta id et.', '5.jpg', '2019-10-25 08:51:55', 4);
INSERT INTO `article` (`art_id`, `art_title`, `art_content`, `art_media`, `art_date`, `usr_id`) VALUES
(37, 'Sapiente dolor sit commodi consequuntur.', 'Ratione eligendi velit delectus impedit. Quas commodi rerum provident nobis et. Laudantium eum est optio. Aut ea praesentium voluptatum alias perferendis et. Ut voluptatem aspernatur qui illo est architecto. Fugiat sunt esse eligendi eveniet odit suscipit ab vel. Et quas molestias quos autem assumenda aspernatur. Suscipit sit minus veniam tempora sint voluptates quo quo. Suscipit ducimus excepturi nesciunt quia ipsum dolorem. Aut at quia porro non autem porro qui. Aliquam ipsum qui ipsa amet adipisci corrupti explicabo. Amet cumque excepturi nulla quo modi et ratione. Distinctio nostrum repellat nihil veritatis saepe. Amet beatae qui aut ea ut. Suscipit iste nemo voluptatem fuga. Laudantium et molestiae dolores dolore. Reprehenderit qui in ad consequuntur cum et quis. Dolore non dolor dicta possimus. Nihil architecto explicabo eos. Temporibus temporibus ab qui numquam at placeat. Et corporis error alias repellendus. Facere vel nobis sunt maxime. Consequuntur distinctio quaerat odio quis officia. Laborum consequatur suscipit molestiae et voluptatibus eum voluptatem voluptatem. Minus possimus tempore sapiente est iusto itaque ab animi. Omnis saepe voluptatem qui. In quas totam ipsa praesentium quasi quo. Illo delectus voluptas eius. Commodi cum laboriosam reiciendis non sunt possimus omnis. Id eligendi veniam qui voluptatem quisquam saepe accusantium. Expedita consequatur in consequatur eos. Sint consequuntur labore velit consequatur et cupiditate voluptatem. Ut est et et porro. Repellendus aperiam maiores rerum nihil molestiae cupiditate fugit. Qui tempora eaque non quod recusandae deleniti. Qui tempora non aspernatur aut deleniti ea dignissimos. Commodi deleniti est praesentium quo vel. Enim consequuntur mollitia dolor rerum optio eligendi. Mollitia velit possimus veritatis cumque perferendis ipsa veritatis assumenda. Excepturi voluptates est minus. Nisi iusto consectetur quas nostrum. Dolore quas ullam eos voluptas quis. Vel aut impedit recusandae dolorem id. Perspiciatis a natus eum sed. Facilis architecto illo debitis dicta et et consequatur quam.', '5.jpg', '2019-09-27 15:47:56', 2),
(38, 'Maiores aperiam error dicta qui dolor autem.', 'Ipsam alias saepe delectus deleniti dolorem non quod. Nesciunt doloribus impedit reprehenderit eius. Aut quis tenetur facilis voluptate. Error ratione pariatur sit explicabo aut et. Voluptatibus dolorem beatae aut hic doloribus maxime. Tempore et perspiciatis qui quisquam. Et velit fugiat eos eligendi error. Sed et ut molestiae modi nesciunt. Rerum voluptatem eum nemo et est veniam maxime. Hic ea eum neque eos recusandae aspernatur. Corporis consequatur autem beatae amet voluptatem non. Corporis enim numquam et reprehenderit est. Magnam alias et optio sed. Sed tempora vel vel nemo eius ullam saepe. Explicabo incidunt et modi debitis ut quod omnis impedit. Non quia eligendi quo recusandae beatae. Alias cupiditate praesentium quia. Sunt dolor nesciunt optio ipsam nesciunt distinctio. Aut mollitia totam sequi mollitia excepturi quod necessitatibus. Dolores laborum exercitationem rerum necessitatibus qui voluptates. Dolore voluptate sit cupiditate voluptate deleniti. Repellendus atque et quisquam. Et incidunt sapiente enim quia velit illum ipsa corrupti. Molestiae inventore commodi harum quaerat sit. Adipisci est sed nulla ullam. Blanditiis velit doloremque atque aut temporibus. Amet quas aperiam officiis temporibus. Minus reiciendis voluptas eligendi qui. Hic ut sit voluptatem accusantium quo fugiat aliquam. Labore nostrum rerum aut harum. Aut et at enim et distinctio. Neque est odit omnis sequi consequatur. Ut esse eos doloremque repudiandae at nisi iste non. Distinctio molestiae et quia et. Nisi necessitatibus vel tenetur itaque nihil distinctio. Officia voluptatum placeat ea. Corrupti aperiam aut repellendus assumenda voluptatem. Sed pariatur consequatur cumque deleniti iusto hic. Quisquam dolores dolor placeat quis.', '5.jpg', '2019-10-26 18:35:57', 10),
(39, 'Magnam delectus praesentium nihil dignissimos consectetur dolorum tempora tenetur aliquam earum.', 'Quam repudiandae qui aut fugiat dicta. Animi aliquam qui veniam assumenda. Necessitatibus fugiat ut delectus repudiandae recusandae aut. Omnis et magni autem itaque ut eos voluptatem. Inventore quia fugit odit nobis ipsam aut. Rem voluptas molestias eaque sed. Occaecati voluptatum accusantium numquam eligendi. Itaque delectus molestias cum dolores non. Expedita rerum doloribus dolores quo. Illo ea explicabo eos ut iste. Consequatur quibusdam necessitatibus nihil libero. Alias aut et adipisci sint sunt. Sed quis placeat id aut est provident alias facere. Deserunt ipsum magnam vero ratione fugit quod distinctio. Debitis sunt qui soluta ea quo. Facere omnis dolor quam ipsam ipsum libero. Alias consequatur quia vero enim occaecati eum ab quis. Molestiae ut ipsam a quae. Dolorum sed temporibus commodi repellendus. Tempora vitae id ea ut itaque a iusto. Error dolorum dolor aut iusto aut aut porro voluptas. Est magni est asperiores aspernatur reprehenderit. Error voluptatem accusantium et quaerat excepturi incidunt quasi. Et reprehenderit vel ut quasi quibusdam voluptatem nihil. Tempore ratione quia soluta. Quibusdam voluptate aperiam ut autem. Voluptate perferendis numquam qui provident consequatur vel. Nulla nulla et enim error. Repellendus et consequatur esse fuga facere. Corrupti tenetur debitis ut quaerat possimus enim. Sunt temporibus quia omnis. Perspiciatis ea fugit temporibus vitae hic. Vel natus fugiat aut harum ipsa doloremque. Odit quaerat quibusdam sit vero quia. Qui in inventore amet non earum rerum. Blanditiis est ut nostrum mollitia. Dolorum vel ut ab quia ea cum eius. Sequi dolorem consequuntur accusantium molestiae vitae eius aliquid iure. Aut commodi qui eligendi. Et tempora amet adipisci qui dolor. Est ut est aperiam. Qui soluta et dolores. Labore assumenda laborum eos quidem. Amet ea reiciendis occaecati molestias animi distinctio. Debitis sequi autem ad et. Sed neque voluptate eos qui et iste ullam. Iste nulla voluptate rerum et facere neque aperiam. Libero enim laborum aperiam et quisquam quam et provident. Vel distinctio facilis qui quia debitis tempore sunt ipsa. Rerum sed ut enim at modi laudantium. Enim tenetur odit et aut autem. Vitae quae dicta doloremque sed corporis non.', '5.jpg', '2019-10-25 21:01:06', 10),
(40, 'Quae ut sit quasi nihil totam.', 'Dolores rem non incidunt aut est eius veritatis. Consequatur autem quod voluptatum quo sed. Quisquam quia dolorum sed. Voluptatem asperiores aut eaque. Quis voluptate minima autem et distinctio. Consectetur sapiente voluptatum laborum quo excepturi. Eaque ullam ipsa officia molestias ut. Quod exercitationem maxime et adipisci. Dolorum consequatur alias qui dicta et id corporis. Recusandae fugit sed cumque in molestiae rerum laudantium. Atque amet aut non sed. Sed maiores quia dolorem voluptas. Debitis repellat omnis dicta quae ut qui voluptates. Impedit est nostrum quisquam sapiente qui. Doloribus est non ut. Nihil iure et dignissimos fugiat aut provident. Sapiente aperiam minus non omnis. Asperiores ex eum iure labore cupiditate reiciendis. Qui totam dolorem eum magni laborum. Et ut qui iste animi. Deleniti repellendus earum deleniti aut praesentium tempore voluptatem. Sint possimus cum est atque minima. In perferendis quas aut voluptatum repellendus sit ut. Pariatur consectetur provident quidem et ut. Praesentium sed maxime minima ut et ratione reprehenderit. Fugit ut veritatis expedita optio. Nobis vel tenetur unde impedit a quibusdam nisi. Est pariatur dolorum ut aliquid. Eligendi delectus deleniti ipsum tempora. Non sed nam veritatis sequi. Temporibus ducimus illum quod nam totam iusto commodi. Exercitationem beatae quaerat aut minus asperiores mollitia est. Numquam quisquam sed non adipisci est adipisci. Nulla ullam sunt ut vel. Voluptatibus accusantium sed culpa. Voluptatem enim corrupti ut culpa. Eum enim aliquam cum omnis sapiente. Molestiae dolorum voluptatem animi vel enim quo. Sed exercitationem officia provident adipisci dicta possimus. Occaecati aut maxime maxime culpa odio aut. Accusamus earum laudantium quos dignissimos vitae ipsum mollitia. Ut esse sed eligendi maiores libero. Laudantium tempore inventore alias quasi illum quia. Voluptatum omnis nihil vel ipsa quia omnis dignissimos. Eos sunt quia officia officiis quae. Id est aut suscipit quo repudiandae corporis. Fugiat ad voluptatibus quasi voluptatem dolores velit et. Aspernatur laborum eius illum debitis eveniet. Similique consectetur amet quas ullam. Eum et necessitatibus repellat est. Quis quia perspiciatis natus necessitatibus. Error commodi soluta est aut velit labore. Magni occaecati necessitatibus repudiandae velit et quod labore. Enim fuga placeat qui fugit quasi nihil molestias quia. Adipisci expedita ut quos mollitia nulla. Sint officiis id explicabo et id. Optio voluptas soluta quibusdam tempora quia molestiae. Sed nobis corporis ducimus. Perferendis optio perspiciatis aperiam.', '5.jpg', '2019-11-13 14:07:07', 5);

-- --------------------------------------------------------

--
-- Structure de la table `comment`
--

CREATE TABLE `comment` (
  `com_id` int(11) NOT NULL,
  `com_content` text NOT NULL,
  `com_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `art_id` int(11) NOT NULL,
  `usr_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `comment`
--

INSERT INTO `comment` (`com_id`, `com_content`, `com_date`, `art_id`, `usr_id`) VALUES
(1, 'Et occaecati hic illo facere aut iste inventore hic. Modi eius at commodi doloribus ipsa sint id. Ut molestiae magnam iste et minima. Aut laboriosam in harum temporibus. Sequi quasi alias ut quis. Et voluptatibus sint sunt in nisi voluptatem. Minima aspernatur deleniti officia aut. Et quia consequuntur eius nam aut.', '2019-11-06 01:16:50', 30, 2),
(2, 'Rem reiciendis rerum officia. Eos dolore dolorem corrupti recusandae rerum. Necessitatibus unde rerum qui quas. Doloremque illo est qui dolor quis sint. Consequatur excepturi et veritatis sapiente pariatur dolorem. Natus vel eos totam aut ut porro reiciendis. Ut aliquid qui maiores.', '2019-11-10 00:50:52', 9, 18),
(3, 'Vitae provident quibusdam aut cupiditate sit dolorum. Animi amet autem voluptatem. Quam quo quos in qui consectetur.', '2019-10-04 16:44:13', 8, 16),
(4, 'Blanditiis molestiae qui ut quis voluptatum ratione officia. Corporis soluta dolor sunt distinctio rerum et. Et non eum voluptatem. Rerum sint quia et similique ut vitae. Qui sed fugiat ut facere aliquid eaque. Omnis maxime nobis aspernatur quisquam voluptates nobis. Error et velit neque nulla porro laudantium. Voluptatum laudantium quisquam sit est. Ab esse adipisci ea illo rerum ratione est necessitatibus. Sit numquam eligendi aut magnam est. Dolore alias totam quae veniam ex est. Autem recusandae dicta qui ex. Recusandae voluptatem et odit deserunt soluta amet. Totam eos deserunt facere excepturi. Magni non id aliquam nesciunt ut et dolor. Voluptatum praesentium aut ducimus autem dolores suscipit.', '2019-10-14 15:15:15', 27, 18),
(5, 'Ad odit repellat dignissimos nam dicta. Corrupti dolor quos fuga molestiae ex. Et omnis eos consequatur maxime. Placeat libero consequatur occaecati nesciunt veritatis est qui. Necessitatibus accusamus et sapiente ratione quod numquam ullam. Tempore reprehenderit vel aspernatur officia officiis ut autem.', '2019-09-13 23:56:15', 3, 13),
(6, 'Et est totam impedit aut nisi maiores. Doloribus asperiores autem consequatur aut cum veniam. Laudantium nihil voluptates et quas ducimus. Odio ea at ut illo dolorem sit recusandae rerum. Optio repellendus placeat doloremque culpa. Cum nihil sit at eum voluptatem in quis. Dignissimos atque nihil blanditiis. Vero quo omnis sapiente tempore consequatur totam. Illo quaerat ipsa omnis voluptatem consequatur eum ea. Et et officiis dolor. Aut quia nostrum dicta ut. Consequatur ab facere ut velit ipsum fuga dicta. Harum est deleniti et nemo nam commodi. Nihil voluptas pariatur debitis praesentium voluptates omnis. Sint et cupiditate nihil cum. Sit et et vitae. Maiores cum enim eius commodi vel.', '2019-10-01 02:37:16', 2, 16),
(7, 'Est harum dolores maxime consequatur incidunt hic. Minima eaque deserunt nostrum aut impedit. Sit et voluptatem possimus esse excepturi. Consequuntur ex quia non qui sit. Sit a ipsa sed dolorum ad quam. Dolore molestiae autem quibusdam dolorem repellat repudiandae nemo debitis. Blanditiis alias qui harum doloribus consectetur qui provident consequatur. Et reprehenderit quis et voluptatem vel quia. Nobis vel quo quidem odio alias necessitatibus doloribus. Omnis ut sit ea corporis. Provident suscipit eaque quo est. Itaque esse nesciunt vel dolor. Eum ipsa ipsam nemo. Est id molestiae quia enim alias eveniet ea. Dolores eaque ut temporibus excepturi voluptas sapiente. Voluptas eius veritatis optio porro sunt qui.', '2019-10-29 01:18:18', 12, 15),
(8, 'Alias nulla blanditiis mollitia porro reprehenderit quaerat. In inventore sapiente non nihil vitae vel. Porro consectetur voluptatem in et. Suscipit molestiae quis laboriosam molestiae quo aut. Porro provident animi ipsam commodi. Inventore ipsam deserunt magni minima. Rem nulla est nesciunt ut. Ut alias molestiae est veritatis id recusandae. Sit mollitia temporibus asperiores totam suscipit. Sint dignissimos earum ratione odit. Nobis temporibus maiores vel eaque et ipsam optio maxime. Ut asperiores facere totam vel. Exercitationem quisquam autem veniam. Magnam commodi sint facere voluptatem. Et laboriosam est est natus dolores eius ex. Dignissimos et dolor tenetur aut aut dolor impedit. Ut itaque eligendi illo. Ipsum ut autem et veritatis. Eum at at qui illo fuga aliquam aut. Temporibus qui sit corporis est. Inventore praesentium quaerat asperiores optio debitis.', '2019-11-06 10:41:19', 4, 5),
(9, 'Aut architecto deleniti unde ducimus et eum recusandae. Quo architecto reprehenderit consequatur repudiandae at quae dolores. Aut assumenda quia ipsam omnis ut. Cupiditate earum atque expedita animi officiis minima. Sint voluptatem quasi quidem consequatur mollitia. Ipsa eum ut dolore dolores culpa ea. Quisquam ut tempore eius voluptate. Ex voluptate distinctio maxime ipsa laboriosam. Dolor repellat ut consequuntur in odit nihil doloribus. Quis consequatur porro incidunt voluptate consectetur pariatur eaque. Tenetur nulla quis assumenda veritatis non. Iste qui quis et aut ipsam fugiat.', '2019-11-12 18:38:19', 21, 3),
(10, 'Aut.', '2019-09-19 14:29:35', 1, 16),
(11, 'Sunt sed et eligendi.', '2019-11-20 03:27:35', 20, 20),
(12, 'Ut nesciunt quisquam necessitatibus incidunt.', '2019-11-02 12:11:36', 17, 15),
(13, 'Quae vel qui eius voluptatem ut.', '2019-11-10 04:05:37', 36, 7),
(14, 'Molestiae dicta.', '2019-10-26 23:55:37', 5, 17),
(15, 'Sint aliquid eveniet odio ad. Dicta animi dignissimos eum non. Culpa dicta illo accusantium rem.', '2019-09-17 20:15:50', 21, 18),
(16, 'Repudiandae ut distinctio sequi. Cumque ut ex et corrupti. Totam et qui culpa doloremque sunt suscipit aliquid. Ea architecto ut facilis sunt fugit. Mollitia amet id rem eum eos. Aperiam aut ut beatae culpa eius et dolores debitis. Omnis officiis dicta rem nemo. Qui ea et aliquam et ut minima. Non sed aut autem laudantium non placeat. Sed sed tempora tempora at officiis qui ipsum.', '2019-10-05 13:26:51', 28, 11),
(17, 'Eum molestiae magni dolorum. Saepe quaerat qui et aut.', '2019-10-22 10:01:52', 13, 19),
(18, 'Vel asperiores maxime excepturi aut esse veniam. Veniam reiciendis error dolorem. Voluptatem quis necessitatibus praesentium quia soluta sit rerum.', '2019-11-21 11:18:52', 28, 9),
(19, 'Dolor qui dignissimos maiores voluptatibus. Consequatur unde dolores rerum dolore.', '2019-11-14 19:41:53', 6, 18),
(20, 'Saepe explicabo est quia libero.', '2019-09-15 10:30:53', 39, 17),
(21, 'Rerum voluptatibus sint rerum temporibus aut qui. Unde vel nostrum quidem. Commodi doloribus iure sunt qui ut. Velit laudantium omnis quia mollitia. Qui magnam consectetur assumenda non pariatur.', '2019-11-06 15:51:54', 2, 20),
(22, 'Eligendi est inventore et et voluptates eos neque ratione. Ut dolore voluptatem nulla. Optio quo natus consequatur rerum unde nisi.', '2019-09-25 03:51:54', 1, 15),
(23, 'Aliquam consectetur fugiat id non unde. Qui sit perferendis aut aut quo.', '2019-09-17 17:30:55', 22, 10),
(24, 'Debitis molestiae eum et hic neque. Totam ea ut aperiam. Error magnam repellat aut soluta libero saepe. Molestiae inventore atque ullam beatae earum totam. Dolorem sed corrupti id delectus. Et perspiciatis magni quis non mollitia qui ratione ipsum. Vitae ducimus aliquid fuga laborum harum animi labore. Aut itaque ratione omnis eaque rerum.', '2019-10-03 04:38:09', 21, 20),
(25, 'Aliquam illo vitae vitae error aliquam molestiae vero.', '2019-11-03 17:41:10', 17, 10),
(26, 'Quo dolorem ut non nihil deleniti et cupiditate. Enim sed nihil exercitationem quidem reprehenderit aut et. Blanditiis temporibus sit enim dolorem quia exercitationem dolore est.', '2019-11-03 11:51:11', 33, 10),
(27, 'Maxime velit veniam incidunt suscipit delectus excepturi. Sit quia deserunt consequatur dolore saepe. Ut ex et sit consequuntur. Animi voluptatibus occaecati blanditiis rem enim ipsum. Ut ex cupiditate tenetur totam dignissimos consequatur perspiciatis. Eius dolores voluptatem tempore magni ad quibusdam. Natus magni a aut nesciunt sit. Occaecati occaecati minus et nam consectetur consequatur.', '2019-09-29 20:03:11', 15, 14),
(28, 'Ducimus quia nulla in rerum quidem quam. Explicabo molestias dolores rem quibusdam. Nemo dicta odio consectetur. Est voluptatem aspernatur atque et quisquam. A velit sed dignissimos suscipit. Eum ullam repellendus praesentium iusto blanditiis. Explicabo nisi et non aut repellat alias. Et voluptatem officiis voluptas architecto illum unde reiciendis.', '2019-10-05 08:33:12', 23, 12),
(29, 'Laudantium vero quo omnis neque assumenda. Itaque quasi perferendis ab impedit ut autem. Et in repellat voluptas culpa laborum occaecati a. Cum sint eum rerum rem est voluptate. Et repellat reiciendis corrupti. Optio dolore tenetur molestias et quo. Quidem aliquid placeat culpa nulla natus. Aperiam soluta provident ut fuga ea. Velit ipsum rerum ut perspiciatis.', '2019-10-30 14:13:12', 3, 10),
(30, 'Quis repellat optio autem. Inventore necessitatibus quisquam soluta rerum. Rerum et assumenda et perspiciatis corrupti eos rem. Sit consectetur aliquam ad neque distinctio dolorem veniam.', '2019-10-02 00:32:13', 1, 4),
(31, 'Dolores quae ut fugiat delectus voluptas quas distinctio. Quod sint corporis animi. Aliquam eius deleniti placeat sit.', '2019-09-19 06:39:14', 23, 10),
(32, 'Repudiandae sequi dolor ea.', '2019-10-29 11:35:58', 3, 8),
(33, 'Deserunt aut enim praesentium quos. Sint quia neque vitae sunt. Vel et magnam vero omnis.', '2019-11-04 23:08:59', 1, 13),
(34, 'Commodi ut quam.', '2019-09-16 16:25:59', 5, 13),
(35, 'Eum.', '2019-10-27 16:23:00', 1, 3),
(36, 'Cum excepturi ea consequuntur dolores iste. In harum ex eum quia saepe inventore. Neque perferendis et dolores consequatur ullam aliquam.', '2019-11-15 20:00:00', 4, 14),
(37, 'Dolor enim omnis est perspiciatis.', '2019-10-21 23:33:01', 3, 9),
(38, 'Harum corrupti voluptatem aliquam libero. Placeat blanditiis dolorum molestias neque. Omnis saepe laudantium officia aut aut dolores. In mollitia consequatur repellat beatae.', '2019-11-12 08:15:19', 1, 8),
(39, 'Voluptas accusamus possimus fugit odio similique explicabo odio. Dolor labore enim soluta aut vero. Et optio qui et sunt quibusdam. Aut cupiditate ratione ab sunt pariatur rerum.', '2019-10-14 03:11:20', 2, 8),
(40, 'Ipsa quod ut aut neque.', '2019-09-25 01:18:20', 2, 12),
(41, 'Aliquid numquam nostrum rerum qui.', '2019-10-26 08:59:21', 4, 16),
(42, 'Architecto hic magnam error modi. Sed ut officiis laudantium ut. Eum nihil similique ratione incidunt magnam vitae. Officia nulla rem omnis natus sint sint quia.', '2019-10-11 05:14:22', 3, 16),
(43, 'Atque aperiam vel qui omnis praesentium animi consectetur facere. Qui maiores rem soluta. Et culpa est neque quia. Beatae odio atque molestias voluptatibus.', '2019-09-18 01:28:44', 37, 8),
(44, 'Beatae aut sequi voluptas omnis. Ad eligendi quisquam illum culpa consequatur. Repellendus quisquam labore inventore illo. Qui quidem veritatis expedita quis et. Eos sed consequuntur ab cum cupiditate est sit veritatis.', '2019-10-13 10:46:45', 36, 14),
(45, 'Est in est commodi earum ut. Ex distinctio occaecati voluptates eveniet ea inventore qui ab. Quos iste eos aut sit. Reprehenderit illum minima placeat aperiam consectetur voluptatem dignissimos. Quis numquam alias rerum neque. Dolores alias enim aliquid quia dolorum.', '2019-09-25 15:34:46', 38, 19),
(46, 'Nam omnis et consequatur aut. Et impedit est esse cum et enim debitis. Rem totam repudiandae quia voluptatibus. Officiis quisquam ut quod saepe. Dolor eos praesentium eos qui laborum. Porro iusto sit provident aut voluptatem ipsum est.', '2019-09-19 12:04:46', 40, 14),
(47, 'Harum dolor id culpa accusamus. Ducimus sed nostrum deleniti earum eos voluptatem. Qui molestiae quam autem earum consequatur.', '2019-11-15 02:04:47', 39, 2),
(48, 'Animi aperiam aliquid enim repudiandae ut repudiandae. Neque voluptatem earum eum.', '2019-09-15 03:39:48', 40, 12),
(49, 'Accusamus sunt enim nihil temporibus omnis illo. Natus eos fugit sed error. Cum in sint at quibusdam necessitatibus sint sit et. Perferendis deleniti iusto vel non voluptatum corrupti.', '2019-11-05 06:03:49', 39, 11),
(50, 'Aliquam.', '2019-10-18 10:34:50', 35, 18),
(51, 'Est soluta architecto rem sit. Maiores voluptatem cum sed et fugiat. Et veritatis minima delectus voluptatem veritatis tempore tempora et.', '2019-11-21 09:45:50', 36, 16),
(52, 'Possimus illum omnis laudantium enim recusandae perspiciatis dolorem unde. Consequuntur nobis similique ut ad sint fugiat maiores. Animi autem sit distinctio. Sit saepe velit perferendis quaerat.', '2019-09-25 17:02:23', 40, 10),
(53, 'Architecto mollitia odio id iure sed quis. Aliquam adipisci voluptas delectus ut. Corporis quia id delectus suscipit.', '2019-11-08 18:04:23', 36, 3),
(54, 'Esse ratione vel aspernatur quia voluptates. Atque optio laboriosam et expedita facilis. Consequatur porro labore dolores. Quaerat non saepe quis nisi dolores non accusantium expedita. Commodi beatae dolorem quas aperiam voluptatem quo.', '2019-09-15 08:12:24', 36, 16),
(55, 'Sapiente dicta officiis sequi. Sit ut sed et aut libero.', '2019-10-17 05:49:24', 35, 11),
(56, 'Cum et dolorum consectetur sed in. Eos veniam atque qui dolor totam sit. Eligendi sequi odio iste at. Odit eaque voluptas cum sit dolor. Doloremque neque est rem magni illum et labore vero.', '2019-10-11 17:37:25', 36, 13),
(57, 'Ea nihil ut quasi. Sequi eveniet enim dolorem. Rerum accusamus corporis nisi eveniet.', '2019-10-14 05:35:26', 40, 13),
(58, 'Ullam accusamus corporis voluptas ducimus quibusdam consequatur. Vel porro autem recusandae tempora et eos. Eaque ut consectetur ut quas. Eum quo nam ut laborum repudiandae quae qui id. Omnis nemo a reiciendis optio architecto et voluptate. Sed libero et enim illo consequuntur. Eligendi omnis ullam ex rerum corrupti quidem sunt. Tenetur explicabo quas quo atque officiis velit.', '2019-10-09 19:26:26', 34, 17),
(59, 'Et explicabo sed consequuntur deserunt veniam qui saepe quisquam. Reiciendis veritatis aspernatur soluta quos et rerum. Doloremque ea distinctio at natus eligendi totam. Nam dicta eos hic quis aperiam eaque reiciendis quia. Commodi impedit dolorum consequatur necessitatibus tempora nam sed. Ducimus et necessitatibus et et quisquam et. Ipsa sed tempora vel.', '2019-10-30 06:49:34', 33, 19),
(60, 'Harum laborum molestias blanditiis quisquam rerum. Numquam a a a impedit. Sit et est et atque et.', '2019-11-14 17:35:35', 38, 6),
(61, 'Corrupti sed doloribus est sed laborum. Corporis fugit expedita blanditiis. Ipsa est laudantium fugit qui voluptas voluptatem illum quis. A excepturi corrupti illum quod. Earum provident eum consequatur assumenda harum temporibus ut tempore. Nihil velit minus quis doloremque velit. Voluptatem doloribus commodi doloribus ducimus placeat alias.', '2019-11-01 15:38:35', 26, 6),
(62, 'Vel enim id doloribus et modi tempora et. Ipsa alias quidem aut excepturi ea nihil tenetur. Nostrum nobis quia sunt ea ipsam. Fuga iste vel nam similique.', '2019-09-23 05:11:36', 27, 4),
(63, 'Est velit omnis earum ut repellat quaerat vel. Quia laborum voluptatum qui in.', '2019-10-01 19:32:36', 25, 9),
(64, 'Sit officiis doloremque omnis accusamus quia cupiditate. Maxime quas nesciunt quis non. Omnis minus molestias perspiciatis itaque voluptas.', '2019-10-12 07:29:36', 39, 6),
(65, 'Atque error molestias.', '2019-11-20 23:48:36', 34, 4),
(66, 'Sint cupiditate nobis unde. Ea excepturi modi ab sint quo dolores blanditiis. Vero ab ducimus nobis et rerum. Qui molestiae eos ea quae doloribus culpa est. Placeat nostrum earum blanditiis quidem tempore. Rerum pariatur eveniet ullam et aut fugiat alias. Rerum et sint corrupti dicta id sequi nulla doloribus. Voluptas laudantium eaque ab soluta tempora veniam. Et iusto soluta corporis quia qui rerum. Qui in iste molestias quod illum.', '2019-09-13 14:28:37', 34, 19);

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

CREATE TABLE `user` (
  `usr_id` int(11) NOT NULL,
  `usr_firstname` varchar(50) NOT NULL,
  `usr_lastname` varchar(50) NOT NULL,
  `usr_email` varchar(100) NOT NULL,
  `usr_password` varchar(100) NOT NULL,
  `usr_status` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`usr_id`, `usr_firstname`, `usr_lastname`, `usr_email`, `usr_password`, `usr_status`) VALUES
(2, 'Diane', 'Lenoir', 'qparent@club-internet.fr', '$2y$10$YZPc0JrmB8qPHqVoyfK17OX.87D1ueY8mHNIT5w2Qk5HbpTsOgs/S', 1),
(3, 'Thierry', 'Lemoine', 'marguerite.allain@noos.fr', '$2y$10$GI/ceNZue82u3ws5AswU3Of9DPvmnWK.RFX3upM2Mv2vFNFdNtwKO', 1),
(4, 'Thibault', 'Carpentier', 'plopez@navarro.com', '$2y$10$Yd.XxrGU9L7sAb8TDHHWw.BCxOCBlrWIoCWNhdmG0Ykmg5wLFmPW.', 1),
(5, 'Élodie', 'Dumas', 'elodie.boutin@noos.fr', '$2y$10$Q.I.VyJfQnieKwLbLuPvHOxPJWI4/ZZh2li3iRabVKJTrbxMqqlMG', 1),
(6, 'Inès', 'Bigot', 'wlabbe@hernandez.com', '$2y$10$W6YuFryWgOD5f3k1qHQggudxu5GW/1oEAtJaAvkSKeoPOOTu5HwVa', 1),
(7, 'Caroline', 'Fischer', 'hgaillard@diaz.net', '$2y$10$1KZNdnPZGWtu7LX1yjuFWOgrzz4yQKvyMQnp50X9CqPns0D54x5Pu', 1),
(8, 'Laurent', 'Jacquet', 'claudine.dupuy@mercier.net', '$2y$10$cXeIEe8JvLloCXIP7c/LDu7AO3mGxs0NvPYDzArK0FOcArvwfKsKO', 1),
(9, 'Théodore', 'Barbe', 'edouard.duhamel@club-internet.fr', '$2y$10$K6DKig037mbJfK/H9zgcMO6312PzlQgO3hmZkwrRpnRJIOuaL9WqO', 1),
(10, 'Étienne', 'Delorme', 'paul.pasquier@lecomte.fr', '$2y$10$oQwtWi/CKJStDTRVps3pJesk9WAzOODZn1hO9OcHy.zvuYTUh50Qu', 1),
(11, 'Élise', 'Faivre', 'marcel05@club-internet.fr', '$2y$10$fn2qi1.fCcWtMro8w7sEUOtWuubN6p9k8/.semS/sRf6uqpOHXBc.', 1),
(12, 'Bertrand', 'Lesage', 'xdias@sfr.fr', '$2y$10$XCMe7CEnusgQKzzad/lZ/.3T5sCXkcYMY85A15/rzDBABzXdKG6tC', 1),
(13, 'Roger', 'Etienne', 'yauger@baudry.fr', '$2y$10$J/2pfRSaWsz0.Nw4vCtvv.lCk1wYlDwHZL1HjMY0NK8hBA0R5Hgt2', 1),
(14, 'Guillaume', 'Bailly', 'bmasse@wanadoo.fr', '$2y$10$ABfXj6I.hdpFsPwm0T4KLeW4euK18xy9ervuHyPucFnSJ64dEdWje', 1),
(15, 'Aimé', 'Pereira', 'christine95@club-internet.fr', '$2y$10$noEU0ijI.Y60FUCDa07FtO8rXNfYus.zq9tk6tq5BfIVJb3YLmm5y', 1),
(16, 'Roger', 'Le Gall', 'kallard@lombard.fr', '$2y$10$KW5kuZwknBT27KqIMVxCmem.pRCdVKhF9IZv2qerX1dQ4BKsqHOD6', 1),
(17, 'Jeanne', 'Dubois', 'zoe10@georges.com', '$2y$10$kRIoOmVvfVFFw1m/MYtd3eRPSHd3./SkTA3Wa45OIq.aCM7VZq8Si', 1),
(18, 'Thibault', 'Joseph', 'cohen.emilie@guillot.com', '$2y$10$Z9n0q2ctrD6IEpNk45zgQeq9Uehq4Wd2fluLYKHF/b3FwhUxy09s6', 1),
(19, 'Margaret', 'Leclercq', 'ydaniel@diaz.fr', '$2y$10$yiH5AjA3fj1UkM/8P5zOG./WqvDZucVJ/X6l/cPxsFlP2s3nAan/K', 1),
(20, 'Denise', 'Lemaitre', 'hleduc@bouvier.fr', '$2y$10$aKQY7/37CUtjyIgnzhVf1eqZ0M8HLlh.jRtzaL0iStYcPwESuEEcK', 1);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `article`
--
ALTER TABLE `article`
  ADD PRIMARY KEY (`art_id`),
  ADD KEY `art_usr_id` (`usr_id`);

--
-- Index pour la table `comment`
--
ALTER TABLE `comment`
  ADD PRIMARY KEY (`com_id`),
  ADD KEY `com_usr_id` (`usr_id`),
  ADD KEY `com_art_id` (`art_id`);

--
-- Index pour la table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`usr_id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `article`
--
ALTER TABLE `article`
  MODIFY `art_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

--
-- AUTO_INCREMENT pour la table `comment`
--
ALTER TABLE `comment`
  MODIFY `com_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=67;

--
-- AUTO_INCREMENT pour la table `user`
--
ALTER TABLE `user`
  MODIFY `usr_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `article`
--
ALTER TABLE `article`
  ADD CONSTRAINT `art_usr_id` FOREIGN KEY (`usr_id`) REFERENCES `user` (`usr_id`);

--
-- Contraintes pour la table `comment`
--
ALTER TABLE `comment`
  ADD CONSTRAINT `com_art_id` FOREIGN KEY (`art_id`) REFERENCES `article` (`art_id`),
  ADD CONSTRAINT `com_usr_id` FOREIGN KEY (`usr_id`) REFERENCES `user` (`usr_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
